### ISSUE TITLE
Default RouteConfig

### ISSUE THREAD

**Issue by necampanini** [jebert142/seniorProjectSideProjects#1]
Currently, when I try to to F5 the project, it gives me a YSOD. Find out why. 

Hint: check the "defaults" argument for the only route specified in the RouteConfig.cs

**Comment by jebert142** [comment]
I changed the RouteConfig file to reflect the name of the MenuController instead of the HomeController. I'm pretty sure this fixed the issue with the ysod, but I'll let you close the issue.

**Comment by necampanini** [comment]
Possible red herring, but that still needed to be done, thanks!
